---
abstract: 'Extend ORLite to support remote SQLite databases'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  IO::Compress::Bzip2: 2.011
  IO::Compress::Gzip: 2.011
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: ORLite::Mirror
name: ORLite-Mirror
no_index:
  directory:
    - inc
    - t
requires:
  File::HomeDir: 0.69
  File::Path: 2.04
  File::Remove: 1.40
  File::Spec: 0.80
  IO::Uncompress::Bunzip2: 2.011
  IO::Uncompress::Gunzip: 2.011
  LWP: 5.806
  ORLite: 0.13
  Params::Util: 0.33
  URI: 1.35
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.07
